config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, :address, :description, :price_per_night, :number_of_guests, presence: true
  validates :price_per_night, :number_of_guests, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    if @flat.update(flat_params)
      redirect_to flat_path(@flat)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :picture_url, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<div class="container">
  <h1>Edit</h1>
  <%= simple_form_for @flat do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :picture_url %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
    <%= f.submit class: "btn btn-primary mt-4" %>
  <% end %>
</div>

app/views/flats/index.html.erb
<div class="container">
  <h1>All Flats</h1>

  <div class="row row-cols-1 row-cols-md-3 g-4">


      <% @flats.each do |flat| %>
        <div class="col">
          <div class="card h-100">
            <img src="<%= flat.picture_url %>" class="card-img-top h-50" alt="...">
            <div class="card-body">
                <h5 class="card-title"><%= flat.name %></h5>
                <p> <i class="fa-solid fa-user-group"></i> <span><%= flat.number_of_guests %> </span> <i class="fa-sharp fa-solid fa-euro-sign"></i> <span><%= flat.price_per_night %></span></p>
                <h6 class="card-subtitle mb-2 text-muted"><%= flat.address %></h6>
                <p class="card-text"><%= flat.description %></p>
            </div>
            <div class="card-footer">
                  <%= link_to "See", flat_path(flat), class: "btn btn-primary" %>
                  <%= link_to "Edit", edit_flat_path(flat), class: "btn btn-warning" %>
                  <%= link_to "Remove", flats_path, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-danger" %>
              </div>
          </div>
      </div>
      <% end %>


  </div>
</div>

app/views/flats/new.html.erb
<div class="container">
  <h1>Add new flat</h1>
  <%= simple_form_for @flat do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :picture_url %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
    <%= f.submit class: "btn btn-primary mt-4" %>
  <% end %>
</div>

app/views/flats/show.html.erb
<div class="container d-flex flex-column">
    <img src="<%= @flat.picture_url %>" class="w-100 h-50">
  <div class="p-4 shadow-4 rounded-3" style="background-color: hsl(0, 0%, 94%);">
    <h2> <%= @flat.name %> </h2>
    <p> <%= @flat.address %> </p>
    <p> <i class="fa-solid fa-user-group"></i> <%= @flat.price_per_night %> <i class="fa-sharp fa-solid fa-euro-sign"></i> <%= @flat.number_of_guests %> </p>

    <p>
      <%= @flat.description %>
    </p>
    <%= link_to "Edit", edit_flat_path, class: "btn btn-warning" %>


  </div>
  <%= link_to "Back to index", flats_path, class: "btn btn-primary" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>